### ISSUE TITLE
Error to reproduce results

### ISSUE THREAD

**Issue by devbaraus** [M-T3K/BiometriaVoz2K21#1]
Hi, I'm studying biometry using voice and I found your work, but I can't make your jupyter notebook work. I tested on linux ubuntu 20.04 and on Google Colab, neither of them worked. Below is the error I get on "Definición del modelo 1" topic:

Input shape: (374, 129, 1)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-ef73bc40831f> in <module>()
     11 
     12 norm_layer = preprocessing.Normalization()
---> 13 norm_layer.adapt(spectrogram1_ds.map(lambda x, _: x))
     14 
     15 model1 = models.Sequential([

9 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    984           except Exception as e:  # pylint:disable=broad-except
    985             if hasattr(e, "ag_error_metadata"):
--> 986               raise e.ag_error_metadata.to_exception(e)
    987             else:
    988               raise

ValueError: in user code:

    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_preprocessing_layer.py:152 adapt_step  *
        self._adapt_maybe_build(data)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_preprocessing_layer.py:267 _adapt_maybe_build  **
        data_shape_nones = tuple([None] * len(data.shape))
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/tensor_shape.py:855 __len__
        raise ValueError("Cannot take the length of shape with unknown rank.")

    ValueError: Cannot take the length of shape with unknown rank.

**Comment by M-T3K** [comment]
Olá Bruno, nos também tivemos alguns problemas. Acho que é por os recursos da computadora, que a RAM nao é suficiente.
